


fishSpecies = {}
fishSpecies['Rock_Beauty'] = {
'''
cctttatttactatttggtgcttgagctggaatagtgggaacggctttaagcctgctaat
tcgagcagagctaaaccaaccaggcagcctccttggcgacgaccagatctataatgtcat
cgttacagcacatgcatttgtaataattttttttatggtcatacccgctataattggggg
atttggaaactgactaattcctctaataatcggggcccccgacatggcattcccccgaat
gaataacataagcttttgacttctccctccctcccttctccttcttctagcatccgctgg
ggtagaagctggggccggaactggatgaacagtttacccacccctagcgggtaatctagc
acatgcgggcgcatccgtagatttaaccatcttctcccttcatttagcaggagtttcctc
aattctgggggctattaattttatcacaacgatcatcaatatgaagcctcctgctatctc
tcagtatcaaacacccctatttgtctgagcagtattaatcacagcagtcctactacttct
ttctcttccagttcttgctgcaggtattacaatactcttaacagaccgaaatttaaacac
caccttcttcgaccctgcaggagggggagacccaattctttaccaacacttattc
'''}

fishSpecies['French_Angelfish'] = {
'''
cctctatttactatttggtgcttgagccggaatggtaggcactgctttgagcctactaat
tcgagccgagctaaatcaaccgggcagccttctcggagacgaccagatctacaatgttat
cgttacagcacacgcattcgtaataattttttttatggtgatgcccgccatgatcggagg
ctttggaaattgattagtcccactaataattggagccccagacatagcatttcctcgaat
aaataatataagcttttgactcctgcccccttctcttcttcttctccttgcttccgccgg
ggtagaggccggagctggaactgggtgaacagtttacccgcccctagctggcaatctagc
ccacgcaggagcatccgtagacctgaccatcttctccctccacctggccggaatctcctc
aattctaggggctattaactttatcacaaccattattaacataaaaccccctgctatttc
acaataccaaactccactatttgtgtgagctgtcctaattactgcagtgctacttctgct
ttctctccccgtccttgctgccggcatcacaatgcttcttacagaccgaaatcttaatac
tactttctttgaccctgcaggagggggagacccaattctttaccagcacttg
'''

}


